spring:
    datasource:
        url: jdbc:h2:mem:discordMetrics
        username: discordMetrics
        password: discordMetrics
        driverClassName: org.postgresql.Driver
    jpa:
        spring.jpa.database-platform:  org.hibernate.dialect.PostgreSQLDialect
discord:
    apiKey: ""